-- ⚠️  DO NOT RUN THIS MIGRATION AGAINST THE SHARED PROJECT ⚠️
--
-- These identity tables (home_accounts, classes, pupils, pupil_parent_links)
-- are OWNED BY wrife-website and already exist in the shared Supabase project
-- (gzmgjkbtsvezfclmreru). They are maintained via wrife-website migrations.
--
-- DWP uses those shared tables directly — it does NOT create its own copies.
-- This file is kept for reference only. Running it would create orphaned
-- duplicate tables and break the cross-app auth model.
--
-- Per wrife-brand-ecosystem skill — table ownership rule:
--   wrife-website owns: home_accounts, classes, pupils, pupil_parent_links
--   wrife-dwp owns: dwp_levels, dwp_progress, dwp_attempts, dwp_daily_*,
--                   dwp_garden_*, dwp_badges, dwp_daily_prompts
--
-- This migration was written when DWP was prototyped as a standalone app
-- with its own Supabase project. That approach was superseded — all WriFe
-- sub-apps share gzmgjkbtsvezfclmreru.
